# Generated by Django 6.0.1 on 2026-01-29 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_balance_alter_transaction_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('IN', '입금'), ('OUT', '출금')], max_length=3, verbose_name='입출금 구분')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('recurring_day', models.IntegerField(verbose_name='실행일 (매달)')),
                ('merchant', models.CharField(blank=True, max_length=100, verbose_name='가맹점/거래처')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('last_executed', models.DateField(blank=True, null=True, verbose_name='마지막 실행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='transactions.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recurring_day'],
            },
        ),
    ]
