# Generated by Django 6.0.1 on 2026-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='거래 후 잔액'),
        ),
    ]
