# Generated by Django 6.0.1 on 2026-01-30 06:56

from django.db import migrations


def add_satisfaction_categories(apps, schema_editor):
    Category = apps.get_model("transactions", "Category")
    categories = [
        ("취미/여가", "OUT", True),
        ("자기계발", "OUT", True),
        ("여행/경험", "OUT", True),
        ("문화/콘텐츠", "OUT", True),
    ]
    for name, cat_type, is_satisfaction in categories:
        Category.objects.get_or_create(
            name=name,
            defaults={"cat_type": cat_type, "is_satisfaction": is_satisfaction},
        )


def remove_satisfaction_categories(apps, schema_editor):
    Category = apps.get_model("transactions", "Category")
    Category.objects.filter(
        name__in=["취미/여가", "자기계발", "여행/경험", "문화/콘텐츠"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_category_is_satisfaction_goal'),
    ]

    operations = [
        migrations.RunPython(
            add_satisfaction_categories,
            remove_satisfaction_categories,
        ),
    ]
